ALTER TYPE "ExtractedFactType" ADD VALUE IF NOT EXISTS 'LOCATION_MENTION';
ALTER TYPE "ExtractedFactType" ADD VALUE IF NOT EXISTS 'LOCATION_ALIAS';
ALTER TYPE "ExtractedFactType" ADD VALUE IF NOT EXISTS 'LOCATION_HIERARCHY';
ALTER TYPE "ExtractedFactType" ADD VALUE IF NOT EXISTS 'LOCATION_ATMOSPHERE';
ALTER TYPE "ExtractedFactType" ADD VALUE IF NOT EXISTS 'LOCATION_ARCHITECTURE';
ALTER TYPE "ExtractedFactType" ADD VALUE IF NOT EXISTS 'LOCATION_ERA';
ALTER TYPE "ExtractedFactType" ADD VALUE IF NOT EXISTS 'LOCATION_SOCIAL_CONTEXT';
ALTER TYPE "ExtractedFactType" ADD VALUE IF NOT EXISTS 'LOCATION_LIGHTING';
ALTER TYPE "ExtractedFactType" ADD VALUE IF NOT EXISTS 'LOCATION_COLOR';
ALTER TYPE "ExtractedFactType" ADD VALUE IF NOT EXISTS 'LOCATION_RECURRING_OBJECT';
ALTER TYPE "ExtractedFactType" ADD VALUE IF NOT EXISTS 'LOCATION_CHANGE';
ALTER TYPE "ExtractedFactType" ADD VALUE IF NOT EXISTS 'LOCATION_CANDIDATE';

ALTER TYPE "EntityConflictType" ADD VALUE IF NOT EXISTS 'LOCATION_POSSIBLE_DUPLICATE';
ALTER TYPE "EntityConflictType" ADD VALUE IF NOT EXISTS 'LOCATION_ATTRIBUTE_CONFLICT';
ALTER TYPE "EntityConflictType" ADD VALUE IF NOT EXISTS 'LOCATION_PARENT_CONFLICT';

CREATE TABLE "LocationAlias" (
  "id" UUID NOT NULL,
  "locationId" UUID NOT NULL,
  "alias" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "LocationAlias_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "LocationAlias_locationId_alias_key" ON "LocationAlias"("locationId", "alias");
CREATE INDEX "LocationAlias_locationId_idx" ON "LocationAlias"("locationId");

ALTER TABLE "LocationAlias" ADD CONSTRAINT "LocationAlias_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "LocationVersion"
  ADD COLUMN "atmosphere" JSONB,
  ADD COLUMN "era" TEXT,
  ADD COLUMN "socialContext" JSONB,
  ADD COLUMN "recurringObjects" JSONB,
  ADD COLUMN "confidenceScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "sourceFactIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "LocationVersion" ALTER COLUMN "sourceFactIds" DROP DEFAULT;
